### ISSUE TITLE
Video Recorder Interfacing (2)

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#7]
1. Why do we use VNC Viewer for the Raspberry PI?
2. Should we use it for other platforms such as the Beaglebone?

**Comment by vandana-embt** [comment]
1.For the first question VNC is the graphical desktop sharing system and we can see the desktop of the Raspberry Pi inside a window of a computer or a mobile so that we will be able to control it as though we are working on the Raspberry pi itself.
2.Instead of an HDMI cable we can use the VNC  on the Beaglebone black which will give means to connect to the board's graphical interface over IP connection.
